id: A3FF553DE
title: 'Bestower of Supreme Blessings: Guru Yoga of the Great Incomparable Lord Atiśa'
type: translation
pechas:
- I6D82DC8A
- IEC612C69
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:12:03.129327
  last_modified_at: 2023-01-04 12:12:03.129332
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  I6D82DC8A/3AC9: BD0D
  IEC612C69/A9FD: BD0D
